# Use all the 70,000 data points.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import fetch_openml

/home/kaji/snap/jupyter/common/lib/python3.7/site-packages/joblib/_multiprocessing_helpers.py:45: UserWarning: [Errno 13] Permission denied.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))


In [2]:
mnist = fetch_openml(name='mnist_784', version=1)
X, y = mnist['data'], mnist['target']
y = y.astype(np.int8) # I change the data type of y to int8, so I will not need to change it later for each question

# Use 60,000 data points as the full training set, and 10,000 as the test set.


In [3]:
X_train, y_train, X_test, y_test = X[:60000], y[:60000], X[60000:], y[60000:]
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((60000, 784), (60000,), (10000, 784), (10000,))

# Split the full training set to create the training set(55,000 data points, used to update the parameters), and a validation set(5,000 data points)

In [4]:
# split dataset to create training set and test set
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 55000, test_size = 10000)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((55000, 784), (55000,), (10000, 784), (10000,))

# You can design your own neural network(the number of hidden layers, the number of neurons in each hidden layer, the activation function, the optimizer, and any other hyper-parameters. You can also use either a sequential model or non-sequential model)


In [5]:
 pip install --upgrade tensorflow

Requirement already up-to-date: tensorflow in /home/kaji/snap/jupyter/common/lib/python3.7/site-packages (2.4.1)
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install --upgrade tensorflow


Requirement already up-to-date: tensorflow in /home/kaji/snap/jupyter/common/lib/python3.7/site-packages (2.4.1)
Note: you may need to restart the kernel to use updated packages.


In [7]:

import tensorflow as tf
from tensorflow import keras

In [8]:
print("tensorflow version: ", tf.__version__)
# Note that it ends with -tf, highlighting the fact that tf.keras implements the Keras API, plus some extra TensorFlow-specific features.
print("keras version: ", keras.__version__)

tensorflow version:  2.4.1
keras version:  2.4.0


In [10]:

# fashion_mnist = keras.datasets.fashion_mnist
# (X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()
# print(X_train_full.shape)
# print(X_train_full.dtype)


In [11]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.layers


In [17]:
model.layers[1].name


'dense'

In [19]:
model.get_layer('dense').name


'dense'

In [20]:

hidden1 = model.layers[1]
weights, biases = hidden1.get_weights()

In [21]:
weights


array([[ 2.7806319e-02, -1.8793985e-02,  5.4852575e-02, ...,
        -4.2535365e-05, -2.6252255e-02, -3.7588481e-02],
       [ 3.5951830e-02,  4.7240891e-02, -2.9055562e-02, ...,
        -3.1521533e-02,  6.2397093e-02, -1.6181320e-03],
       [-4.7788616e-02,  2.3826905e-02,  4.0649116e-02, ...,
         6.0281083e-02, -5.3678825e-02, -2.0478051e-02],
       ...,
       [-2.4669968e-02, -6.4085960e-02, -1.4269341e-02, ...,
        -3.0283820e-02,  3.0400254e-02, -4.9291551e-04],
       [-4.4443734e-02, -2.2626195e-02,  2.1609001e-02, ...,
         5.1471546e-02, -1.0830358e-02,  7.0653066e-02],
       [-3.0023463e-02, -1.9743294e-03, -6.3147984e-02, ...,
        -3.4403633e-02, -5.5808734e-02, -3.2827038e-02]], dtype=float32)

In [22]:
weights.shape


(784, 300)

In [23]:
biases


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [24]:
biases.shape


(300,)

In [31]:
model.evaluate(X_test, y_test)


313/313 [==============================] - 0s 699us/step - loss: 119.7072 - accuracy: 0.0891


[119.36878967285156, 0.09000000357627869]

In [32]:
X_new = X_test[:5]
y_proba = model.predict(X_new)
print(y_proba.round(2))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
y_hat = np.argmax(y_proba, axis=-1)
print(y_hat)

[9 9 1 1 9]


In [34]:
X_new = X_train[:3]
y_proba = model.predict(X_new)
print(y_proba.round(2))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:

y_hat = np.argmax(y_proba, axis=-1)
print(y_hat)

[1 9 2]


# Let's take this homework assignment as a CONTEST to see who can achieve the highest accuray on the test set.


In [40]:
model.evaluate(X_test, y_test)


313/313 [==============================] - 0s 417us/step - loss: 15299.0774


15110.2060546875